FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build 
WORKDIR /src 
COPY "MicroservicesCourse.sln" "MicroservicesCourse.sln" 
COPY "Services/Catalog/Catalog.API/Catalog.API.csproj" "Services/Catalog/Catalog.API/Catalog.API.csproj" 
RUN dotnet restore  
COPY "Services/Catalog/Catalog.API"  "Services/Catalog/Catalog.API" 
RUN dotnet publish --no-restore -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM build as publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Catalog.API.dll"]
