FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS publish 
WORKDIR /app 
COPY *.csproj ./ 
COPY . ./ 
RUN dotnet publish -c Development -o out 
 
 
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime 
WORKDIR /app 
COPY --from=publish /app/out . 
ENTRYPOINT ["dotnet", "Catalog.dll"] 
